# Generated by Django 2.0 on 2018-02-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'entities_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeroAcquaintance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HeroProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('entities.hero',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'Heroes'},
        ),
        migrations.AddField(
            model_name='hero',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hero',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots/'),
        ),
        migrations.AddField(
            model_name='villain',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='villain',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='entities.Hero'),
        ),
        migrations.AddField(
            model_name='heroacquaintance',
            name='detractors',
            field=models.ManyToManyField(related_name='_heroacquaintance_detractors_+', to='entities.Hero'),
        ),
        migrations.AddField(
            model_name='heroacquaintance',
            name='friends',
            field=models.ManyToManyField(related_name='_heroacquaintance_friends_+', to='entities.Hero'),
        ),
        migrations.AddField(
            model_name='heroacquaintance',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.Hero'),
        ),
        migrations.AddField(
            model_name='heroacquaintance',
            name='main_anatagonists',
            field=models.ManyToManyField(related_name='_heroacquaintance_main_anatagonists_+', to='entities.Villain'),
        ),
    ]
